name: Publish

on:
  push:
    branches:
      - stable
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
    - name: Build Package
      run: |
         python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: aicspypi
        password: ${{ secrets.PYPI_TOKEN }}
